# ################### GLOBAL ###################

global:
  environmentName: gamma
  gcp:
    projectId: hnt-live-shared # TODO: make sure we don't reuse this on other environments
    gke:
      clusterLocation: us-east4
      clusterName: main-standard-global # TODO: consider templatizing this one

appOfApps:
  default:
    valuesFile: ../../environments/{{ .Values.global.environmentName }}/values.yaml
    spec:
      project: default
      source:
        repoURL: https://github.com/HereNotThere/kerem-argocd-test
        targetRevision: main

  applications:
    - name: external-secrets
      disable: false
      namespace: external-secrets
    - name: argocd
      disable: false
      namespace: argocd
    - name: datadog
      disable: false
      namespace: datadog
    - name: metrics-aggregator
      disable: false
      namespace: default

external-secrets:
  serviceAccount:
    create: true
    name: main-service-account
    annotations:
      iam.gke.io/gcp-service-account: main-service-account@{{ .Values.global.gcp.projectId }}.iam.gserviceaccount.com
# TODO: environment tag does not work
# datadog:
#   datadog:
#     tags:
#       - environment: {{ .Values.global.environmentName }}
