# ################### GLOBAL ###################

global:
  # TODO: go over these keys and pick ones with less collision
  environmentName: gamma # TODO: argocd uses the env key, and expects it to be a list. don't use it here.

appOfApps:
  default:
    spec:
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: default
      source:
        repoURL: https://github.com/HereNotThere/kerem-argocd-test
        targetRevision: main
        helm:
          valueFiles: ../../environments/gamma/values.yaml
  applications:
    - name: argocd-umbrella
      disable: false
      namespace: argocd
    - name: external-secrets-umbrella
      disable: true
      namespace: external-secrets
    - name: datadog-umbrella
      disable: true
      namespace: datadog
    - name: metrics-aggregator
      disable: true
      namespace: default # TODO: should i move this to a separate namespace?
# metrics-aggregator:
#   riverRpcUrl:
#     value: "https://testnet.rpc.river.build/http" # TODO: turn this into a secret
# ################### DATADOG ###################

# datadog:
#   datadog:
#     apiKeyExistingSecret: datadog-secret
#     appKeyExistingSecret: datadog-secret
#     prometheusScrape:
#       enabled: true

#   agents:
#     containers:
#       agent:
#         # resources for the Agent container
#         resources:
#           requests:
#             cpu: 200m
#             memory: 256Mi

#       traceAgent:
#         # resources for the Trace Agent container
#         resources:
#           requests:
#             cpu: 100m
#             memory: 200Mi

#       processAgent:
#         # resources for the Process Agent container
#         resources:
#           requests:
#             cpu: 100m
#             memory: 200Mi

#     priorityClassCreate: true

#   clusterAgent:
#     enabled: true
#     metricsProvider:
#       enabled: true
