# ################### GLOBAL ###################

global:
  environmentName: gamma
  gcp:
    projectId: hnt-live-gamma # TODO: make sure we don't reuse this on other environments
    gke:
      clusterLocation: us-east4
      clusterName: main-cluster # TODO: consider templatizing this one
  chains:
    river:
      chainId: 6524490 # TODO: always update
      contractAddresses:
        riverRegistry: "0xf18E98D36A6bd1aDb52F776aCc191E69B491c070" # TODO: always update this accross environments

appOfApps:
  default:
    valuesFile: ../../environments/gamma/values.yaml
    spec:
      project: default
      source:
        repoURL: https://github.com/HereNotThere/kerem-argocd-test
        targetRevision: main

  applications:
    - name: external-secrets
      disable: false
      namespace: external-secrets
      values:
        external-secrets:
          serviceAccount:
            create: true
            name: main-service-account
            annotations:
              iam.gke.io/gcp-service-account: main-service-account@hnt-live-gamma.iam.gserviceaccount.com # TODO: make sure you replace the project ID with the correct one. turn this into a tpl

    # - name: argocd
    #   disable: false
    #   namespace: argocd
    - name: datadog
      disable: false
      namespace: datadog
    - name: metrics-aggregator
      disable: false
      namespace: default
    - name: notification-service
      disable: false
      namespace: default
      values:
        apnsTownsAppIdentifier: com.towns.internal # TODO: make sure you update this on other environments

