# ################### GLOBAL ###################

global:
  env: gamma
  spec:
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    project: default
    source:
      repoURL: https://github.com/HereNotThere/kerem-argocd-test
    targetRevision: main
  valuesFile: ./environments/gamma/values.yaml
argocdApplications:
  - name: argocd-umbrella
    disable: false
    namespace: argocd
  - name: external-secrets-umbrella
    disable: false
    namespace: external-secrets
  - name: datadog-umbrella
    disable: false
    namespace: datadog
# argocd-umbrella:
#   server:
#     ingress:
#       enabled: true
#     service:
#       type: ClusterIP
# datadog-umbrella:
#   datadog:
#     apiKeyExistingSecret: datadog-secret
#     appKeyExistingSecret: datadog-secret
#     prometheusScrape:
#       enabled: true
# ################### DATADOG ###################

# datadog:
#   datadog:
#     apiKeyExistingSecret: datadog-secret
#     appKeyExistingSecret: datadog-secret
#     prometheusScrape:
#       enabled: true

#   agents:
#     containers:
#       agent:
#         # resources for the Agent container
#         resources:
#           requests:
#             cpu: 200m
#             memory: 256Mi

#       traceAgent:
#         # resources for the Trace Agent container
#         resources:
#           requests:
#             cpu: 100m
#             memory: 200Mi

#       processAgent:
#         # resources for the Process Agent container
#         resources:
#           requests:
#             cpu: 100m
#             memory: 200Mi

#     priorityClassCreate: true

#   clusterAgent:
#     enabled: true
#     metricsProvider:
#       enabled: true
