apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datadog-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: api-key
    remoteRef:
      key: datadog-secret
      version: latest
      property: api-key
  - secretKey: app-key
    remoteRef:
      key: datadog-secret
      version: latest
      property: app-key