apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-store
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.global.gcp.projectId }}
      auth:
        workloadIdentity: 
          clusterLocation: {{ .Values.global.gcp.gke.clusterLocation }}
          clusterName: {{ .Values.global.gcp.gke.clusterName }}
          clusterProjectID: {{ .Values.global.gcp.projectId }}
          serviceAccountRef:
            name: external-secrets 

# ---

# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: my-secret
#   namespace: external-secrets
# spec:
#   refreshInterval: "1h"
#   secretStoreRef:
#     name: gcp-secret-store
#     kind: SecretStore
#   target:
#     name: synced-secret
#     creationPolicy: Owner
#     deletionPolicy: Retain
#   data:
#   - secretKey: key
#     remoteRef:
#       # TODO: use project id from global
#       key: example-secret
#       version: latest
