apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.global.gcp.projectId }}
      auth:
        workloadIdentity: 
          clusterLocation: {{ .Values.global.gcp.gke.clusterLocation }}
          clusterName: {{ .Values.global.gcp.gke.clusterName }}
          clusterProjectID: {{ .Values.global.gcp.projectId }}
          serviceAccountRef:
            name: main-service-account
            namespace: {{ .Release.Namespace }}
