apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: xchain-monitor-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: river-rpc-url
    remoteRef:
      key: rpc_urls
      version: latest
      property: river
  - secretKey: base-rpc-url
    remoteRef:
      key: rpc_urls
      version: latest
      property: base