apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-store-{{ .Values.global.environmentName }}
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    gcpsm:
      projectId: {{ .Values.global.gcp.projectId }}
      auth:
        # With Workload Identity, typically you can leave this empty or specify
        # 'secretRef' if you are using a key file. But for Workload Identity, 
        # you usually just rely on the assigned GSA from the serviceAccount annotation.
        workloadIdentity: {}
