apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-store-{{ .Values.global.environmentName }}
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    gcpsm:
      projectId: {{ .Values.global.gcp.projectId }}
      auth:
        workloadIdentity: 
          clusterLocation: {{ .Values.global.gcp.gke.clusterLocation }}
          clusterName: {{ .Values.global.gcp.gke.clusterName }}
          clusterProjectID: {{ .Values.global.gcp.gke.projectId }}
          serviceAccountRef:
            # TODO: is it a bad idea to attach the default service account to the secret store?
            name: default
            namespace: default