apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: metrics-aggregator-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: metrics-aggregator-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: river-rpc-url
    remoteRef:
      key: rpc-urls
      version: latest
      property: river