apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: services-{{ $.Values.global.environmentName }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $.Values.appOfApps.default.spec.project }}
  source:
    repoURL:  {{ $.Values.appOfApps.default.spec.source.repoURL }}
    targetRevision: {{ default $.Values.appOfApps.default.spec.source.targetRevision .targetRevision }}
    path: charts/app-of-apps
    helm:
      valueFiles:
      - {{ $.Values.appOfApps.default.spec.source.helm.valueFiles }}
  destination:
    namespace: {{ default $.Values.appOfApps.default.spec.destination.namespace  .namespace }}
    server: {{ $.Values.appOfApps.default.spec.destination.server }}
  syncPolicy:
    {{- if not .disableAutomated }}
    automated:
      prune: true # TODO: is this okay?
      selfHeal: true # TODO: is this okay?
      allowEmpty: true # TODO: is this okay?
    {{- end }}
    syncOptions:
      - CreateNamespace=true
---
{{- end }}
{{- end }}